### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by najmehabiri** [rayisaacalan/BASTION#3]
I am installing the git package on MacBook M2, which gives this error:

```R
/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include/Rcpp/sugar/functions/sapply.h:36:19: error: no template named 'result_of' in namespace 'std'; did you mean 'traits::result_of'?
        typedef typename ::std::result_of<Function(typename SugarExpression::stored_type)>::type type;
                         ^~~~~~~~~~~~~~~~
                         traits::result_of
/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include/Rcpp/traits/result_of.h:30:8: note: 'traits::result_of' declared here
struct result_of{
       ^
1 error generated.
```
Have you seen such an error?

**Comment by rayisaacalan** [comment]
Hi Najmeh,
I haven't seen such an error before since I do not have a Mac or Apple Silicon device to troubleshoot on. Thanks for bringing it to my attention. What version of R, clang++, and Rcpp are you using? I suspect that the issue is related to the deprecation of std::result_of in C++17.

https://github.com/RcppCore/Rcpp/commit/2e6cc75eb889856e0751af74b9266af834d323d6

**Comment by najmehabiri** [comment]
Hello, and thank you for answering. I am using:
R 4.2.3
Clang 14.0.3
Rcpp 1.0.10

Do you think this change would help?
```c++
std::invoke_result_t<A, B>
```

**Comment by rayisaacalan** [comment]
I don't think manually changing the definitions from Rcpp would be a good idea since it would break with updates. I haven't been able to replicate the issue myself but I have an idea that might work. I added a new branch "Clang17Fix" where I've manually specified to use C++17 items which hopefully will prevent the trigger `#if __cplusplus < 201703L` in the sapply definition. Could you try that branch and let me know if it works on your machine?

**Comment by najmehabiri** [comment]
Thank you, it worked. 
I first needed to reinstall the new R binary for M1/M2 (released a few days ago).
Then the following additions to ~/.R/Makevars 

```
# homebrew
FLIBS   =-L/opt/homebrew/opt/gfortran/lib
F77     = /opt/homebrew/bin/gfortran
FC      = /opt/homebrew/bin/gfortran

CFLAGS   = -I/opt/homebrew/include
CPPFLAGS = -I/opt/homebrew/include
CXXFLAGS = -I/opt/homebrew/include
```
